### ISSUE TITLE
Clamping positive samples to +126

### ISSUE THREAD

**Issue by viciious** [ed7n/gapcm#1]
Hi!

Thanks for the excellent tool, works great so far! However, I wanted to note a small deficiency in the encoder: the value 0xff is a special value used by the Ricoh PCM chip as a loop marker. This means than +127 is NOT a legal input sample value for the audio. 

More info here: https://segaxtreme.net/threads/sega-cd-pcm-format.13267/

Cheers.

**Comment by BrendonIrwan** [comment]
Hello.

Your feedback is much appreciated.

Once time permits, I will verify this with /Eternal Blue/ and fix the encoder.

Which reminds me: what should happen if my decoder sees a 0xff?

Sources would be great.


Cheers.



sent with FairEmail

2024-02-15T11:39:51Z Victor ***@***.***>:

**Comment by BrendonIrwan** [comment]
Hello again.

I just checked the issue on GitHub and saw the link.

Edits to messages are not sent to my email inbox.

I think I skimmed through that forum thread before so I'll definitely review it once time permits.


Thanks very much.



sent with FairEmail

2024-02-15T14:06:24Z Brendon ***@***.***>:

**Comment by viciious** [comment]
Please refer to page 14 of the official PCM hardware manual: https://segaretro.org/images/2/2d/MCDHardware_Manual_PCM_Sound_Source.pdf

![image](https://github.com/ed7n/gapcm/assets/1173058/f1438dec-f15c-4546-8b6c-d51187edf776)

Not sure why it mentions 253 as the maximum value, 254 should also work. Then again, Sega documentation is known to be of dubious quality.

I suppose the way you'd handle the 0xff in the sample data is up to you.. That special value should not be part of the raw sample data and is only used in the runtime. One strategy would be to simply clamp it to 254 or 253.

**Comment by BrendonIrwan** [comment]
Hello.

Sorry it took a while.

I have corrected the issue and will upload it once I re-encode the sample game PCM files--likely tomorrow.

The maximum of 253 or 0xfd actually refers to the figure in page. Otherwise I think it makes no mention of any special use of 254 or 0xfe.

**Comment by viciious** [comment]
> The maximum of 253 or 0xfd actually refers to the figure in page.

I think that the page is actually wrong about 0xfd. The proper maximum value is 254/0xfe.

**Comment by BrendonIrwan** [comment]
Closing as fixed in Update 0 Revision 6.
